service: mtax-shorturl-service

frameworkVersion: '2'

custom:
  customDomains:
  - domainName: mt.ax
    stage: prod
    basePath: ''
    certificateName: 'mt.ax'
    endpointType: 'regional'
    securityPolicy: tls_1_2
    createRoute53Record: false
  - domainName: www.mt.ax
    stage: prod
    basePath: ''
    certificateName: 'mt.ax'
    endpointType: 'regional'
    securityPolicy: tls_1_2
    createRoute53Record: false
  - domainName: stage.mt.ax
    stage: stage
    basePath: ''
    certificateName: 'mt.ax'
    endpointType: 'regional'
    securityPolicy: tls_1_2
    createRoute53Record: false
  - domainName: dev.mt.ax
    stage: dev
    basePath: ''
    certificateName: 'mt.ax'
    endpointType: 'regional'
    securityPolicy: tls_1_2
    createRoute53Record: false
  dynamodb:
    stages: ['dev']
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: false
    seed:
      domain:
        sources:
        - table: mtax_dev_shorturls
          sources: ['./example_items.json']


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  deploymentBucket:
    blockPublicAccess: true
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:GetItem
      Resource:
        - Fn::GetAtt:
          - shortUrlTable
          - Arn
  environment:
    env: ${opt:stage, self:provider.stage, "dev"}

package:
  patterns:
  - src/**
  - '!.git/**'
  - '!.github/**'
  - '!.gitlab-ci.yml'
  - '!.dynamodb/**'

functions:
  shorturl:
    handler: src/redirect.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{shorturl}
          method: get
  
resources:
  Resources:
    shortUrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: mtax_${opt:stage, self:provider.stage, "dev"}_shorturls
        AttributeDefinitions:
          - AttributeName: shorturl
            AttributeType: S
        KeySchema:
          - AttributeName: shorturl
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
- serverless-domain-manager
- serverless-dynamodb-local
- serverless-offline